services:
  authorbot:
    build:
      context: .
    restart: unless-stopped
    stop_signal: SIGINT
    stdin_open: true
    tty: true
    ports:
      - "${EXTERNAL_PORT:-8085}:8080"
    volumes:
      - authorbot-data:/data
    environment:
      DOCKER: "1"
    command:
      - python
      - -m
      - acbot
      - --root
      - --data-root
      - /data

volumes:
  authorbot-data:
